### ISSUE TITLE
Memory issue with Fly

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual-server#73]
I have received an email from Fly telling me that Actual crashed because it ran out of memory, if I increase the memory on Fly I will of course be outside the free tier.

I am unclear as to whether this is a bug in Actual or whether others are going to find that the free allocation of memory on Fly will be insufficient long term.

I think the out or memory occurs when downloading for the first time (or when restoring from an exported file).

**Comment by rich-howell** [comment]
This issue was raised on Discord and while this seems to be slightly different to the issue raised there, the budget isn't being downloaded, I think it is still relevant. 

**Discord Thread:** https://discord.com/channels/937901803608096828/970145959612932136/1001218889369268284

_Response from James_ - "It might be yes, because the server is running the full app. I'm still considering switching to server to use the "simple" sync method by default where it's not. it's way more memory and cpu efficient and we're not utilizing the benefits of the full app sync anyway

I can’t stress how much the “full sync” is doing — it’s literally loading the entire backend of Actual and running it. Actual wasn’t built for this; it assumed it was a client-side app. The code eagerly sets up a lot of stuff the server probably doesn’t need.

The idea was we could leverage more of the app and have stuff like an HTTP API. But we aren’t doing any of that yet so we should probably switch the default implementation"

https://discord.com/channels/937901803608096828/970145959612932136/1001306174399979580
https://discord.com/channels/937901803608096828/970145959612932136/1001309095673987163

**Comment by Kidglove57** [comment]
Thanks Rich - yes I do recall discussions regarding memory use and hopefully it is on the dev agenda. By its nature it gets harder to find things in Discord as the chats developed.

What caused me to raise this again was the unexpected email from Fly themselves. 

In case it is relevant I am running the image for the responsive version, from:

https://github.com/PartyLich/actual-server/pkgs/container/actual-server

**Comment by rich-howell** [comment]
This is potentially going to be resolved with https://github.com/actualbudget/actual-server/pull/75

**Comment by rich-howell** [comment]
Hey @Kidglove57 

Now that we have launched 20.10.25 I belive this is resolved. If you run into issues let me know and I will re-open this issue. 

Cheers
Rich
